theme: jekyll-theme-minimal
title: RV
description: Une brève description de votre site
author: Rodolphe Venot
baseurl: ""
url: "https://rodolphevenot.github.io"

# Configuration de navigation
header_pages:
  - about.md
  - contact.md

# Configuration des posts de blog
show_excerpts: true

# Plugins (optionnels)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
